### ISSUE TITLE
absolute value instead of relative changes? 

### ISSUE THREAD

**Issue by quciet** [mathause/cmip_temperatures#3]
Hi there,

I found this repo very useful for getting the CIMP5 & CIMP6 decadal data, thank you so much! I'm wondering if it is possible to get the absolute value instead of climate anomalies? Or, in the step4 of your methods, you mentioned "Subtract the mean over 1850 to 1900 (inclusive)", would you mind publishing the actual value of the reference period, i.e., **mean over 1850 to 1900**?

Thanks much in advance!

**Comment by mathause** [comment]
I added absolute temperatures in #4.
